#Please choose which program to install by setting to true
Maya = 'true'
CrackMaya ='true'
Listary = 'true'
Flux = 'true'
Zip = 'true'
Bulk_Crap_Uninstaller = 'true'
BleachBit = 'true'
memreduct = 'true'
MicrosoftEdge = 'true'
WindowsTerminal = 'true'